### ISSUE TITLE
Error request not HTTPS

### ISSUE THREAD

**Issue by Michael-RealT** [sannminwin/geoplugin#1]
Hello, I discovered your great plugin, but found myself faced with an error on the site in production, the configuration of the site requires that all requests be in HTTPS, your API does not work in HTTPS.

Would it be possible to make it work in HTTPS?

![image](https://user-images.githubusercontent.com/65588404/155902403-01752945-87ae-4a24-9df8-7ff771b81e01.png)

**Comment by milpatel11** [comment]
@Michael-RealT  This issue is covered in My PR 

pl. review. if you need to use it you can use that module to get fix meanwhile
